# app/models.py
from pydantic import BaseModel, Field

# --- Request Model for /generate endpoint ---
class GenerationRequest(BaseModel):
    prompt: str = Field(..., description="The input text prompt for the LLM.")
    max_new_tokens: int = Field(50, description="Maximum number of tokens to generate.", gt=0, le=512)

# --- Response Model for /generate endpoint ---
class GenerationResponse(BaseModel):
    generated_text: str = Field(..., description="The text generated by the LLM.")